/**
 *
 * @public
 * @namespace Geo
 * @description detect geo location using geo_plugin script in head.
 * Chance location specific options for product page buy button.
 *
 */

const Geo = {
	init(){
		this.geoQuery();

		/*get state of element*/
		this.isActive();

		/* if DOM element is on page run scripts*/
		if(!this.state){
			return false;
		}

		this.cacheDOM();
		
		console.log(this);
	},
	isActive(){

		/*
		 * @desc check to see if DOM element is on page
		*/ 

		let productPage = $('.Product');

		let isActive = productPage.length ? true : false;

		this.state = isActive;
	},
	geoQuery(){

		/* 
		 * @desc get users country location returned as country code
		 *	using geo plugin script in HEAD
		*/
	
		let marketplace = '';

		$.ajax({
			url: "https://ipinfo.io/json",
			success: (data) => {
				switch (data.country) {
					case "US": marketplace = "d011d2c7-0e0d-4905-9f47-57cc0cd923b6"; break;
					case "CA": marketplace = "d011d2c7-0e0d-4905-9f47-57cc0cd923b6"; break;
					default: marketplace = '';
				}

				this.query = data.country;

				/* check if approved country */
				if(this.state) {
					this.checkCountryCode(data.country);	
				}

				if (marketplace.length > 0) {

					$(this.actions[0]).addClass('active-marketplace').attr('data-marketplace', marketplace);

					const script = document.createElement('script');

					$(script).attr({
						type: "text/javascript",
						src: "https://hovercart.quivers.com/?Marketplace=" + marketplace,
						async: "true"
					});

					$('head').append(script);

				}
			}
		});
	},
	checkCountryCode(country) {
		/* 
		 * @desc check if one of the approved countries 
		 * and render either dealer button or quivers add
		 * to cart button
		*/

		const isApproved = (country == "US" || country == "CA");

		if(!isApproved) {
			this.renderDealerButton();
			$('.product-actions .product-price').remove();
		}

		this.addDOMClasses();
	},
	renderDealerButton() {

		/* 
		 * @desc create a button to be rendered in place of 
		 * the add to cart button generated by quivers if 
		 * quivers id is in place
		*/
	
		$(this.actions[0]).addClass('outside-bounds');
		const link = document.createElement('a');

		link.setAttribute('href', '/dealers/');
		link.innerHTML = "Find A Dealer";

		$('.product-buy').html(link);
	},
	cacheDOM(){
		/* @desc cache dom */

		const productPage = $('.Product');

		this.actions = productPage.find('.product-actions');
		this.button = productPage.find('.product-buy a');
	},
	addDOMClasses(){
		/* @desc add active class for CSS styling and country data attribute */
		$(this.actions[0]).addClass('geo-data-active').attr('data-country', this.query);
	}
}

export default Geo;