import axios from "axios";

/**
 * @public
 * @namespace Geo
 * @description detect geo location using geo_plugin script in head.
 * Chance location specific options for product page buy button.
 */

const quivers = {
    init () {
        const productPage = this.checkProductPage();

        this.geoQuery();
        /* if DOM element is on page run scripts*/
        if (productPage) {
            this.cacheDOM();
        }
    },
    loadCart (marketplace) {
        const script = document.createElement("script");

        script.type = "text/javascript";
        script.src = `https://hovercart.quivers.com/?Marketplace=${marketplace}`;
        script.async = "true";

        document.querySelector("head").appendChild(script);
    },
    checkProductPage () {
        let productPage = document.querySelector(".Product");

        if (productPage) {
            productPage = true;
        }

        return productPage;
    },
    /*
     *  @desc get users country location returned as country code
     *	using geo plugin script in HEAD
     */
    geoQuery () {
        let marketplace = "";
        const request = axios.get("https://ipinfo.io/json", {
            headers: {
                "Cache-Control": "no-cache, no-store, must-revalidate"
            },
            params: {
                token: "d3cd176decd4e9"
            }
        });

        request.then((response) => {
                switch (response.data.country) {
                    case "US":
                        marketplace = "d011d2c7-0e0d-4905-9f47-57cc0cd923b6";
                        break;
                        // case "CA": marketplace = "d011d2c7-0e0d-4905-9f47-57cc0cd923b6"; break;
                    default:
                        marketplace = "";
                }

                const productPage = this.checkProductPage();

                this.query = response.data.country;

                if (productPage) {
                    this.checkCountryCode(this.query);
                }
                if (marketplace.length > 0) {
                    if (productPage) {
                        this.actions.classList.add("active-marketplace");
                        this.actions.dataset.dataMarketplace = marketplace;
                    }

                    this.loadCart(marketplace);
                }
            })
            .catch((error) => {
                console.log(error);
            });
    },
    /*
     * @desc check if one of the approved countries
     * and render either dealer button or quivers add
     * to cart button
     */
    checkCountryCode (country) {
        //console.log({ country });
        const isApproved = (country === "US");

        if (!isApproved) {
            //console.log("not approved");
            this.renderDealerButton();
            document.querySelector(".product-actions .product-price").remove();
        } else {
            this.addDOMClasses();
        }
    },
    /*
     * @desc create a button to be rendered in place of
     * the add to cart button generated by quivers if
     * quivers id is in place
     */
    renderDealerButton () {
        this.actions.classList.add("outside-bounds");
        const link = document.createElement("a");

        link.setAttribute("href", "/dealers/");
        link.innerHTML = "Find A Dealer";

        document.querySelector(".product-buy").innerHTML(link);
    },
    /* @desc cache dom */
    cacheDOM () {
        const productPage = document.querySelector(".Product");

        this.actions = productPage.querySelector(".Product__actions");
        this.button = productPage.querySelector(".product-buy a");
    },
    /* @desc add active class for CSS styling and country data attribute */
    addDOMClasses () {
        this.actions.classList.add("geo-data-active");
        this.actions.dataset.dataCountry = this.query;
    }
};

export default quivers;